//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace SSTUTools
{
	public class SSTUMultiDockingPort : ModuleDockingNode
	{

		public string portName = "Port 0";

		public override void OnStart (StartState st)
		{
			base.OnStart (st);
			//rename events to use specified name from config
			Events ["Undock"].guiName = "Undock " + portName;
			Events ["UndockSameVessel"].guiName = "Undock" + portName;
			Events ["Decouple"].guiName = "Decouple " + portName;

			Actions ["DecoupleAction"].guiName = "Decouple " + portName;
		}
	}
}

